-- 우유와 요거트가 담긴 장바구니
SELECT A.CART_ID FROM 
 (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '요거트') as A, 
 (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '우유') as B
 WHERE A.CART_ID = B.CART_ID

-- 입양 시각 구하기(2)
SET @hour := -1;
SELECT
    (@hour := @hour +1) AS 'HOUR',
    (
        SELECT COUNT(DATETIME)
        FROM ANIMAL_OUTS
        WHERE HOUR(DATETIME) = @hour
    ) as COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23

-- 보호소에서 중성화한 동물
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM (SELECT * FROM ANIMAL_INS WHERE SEX_UPON_INTAKE LIKE 'Intact%') as A,
(SELECT * FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%') as B
WHERE A.ANIMAL_ID = B.ANIMAL_ID