-- 오랜 기간 보호한 동물 문제(1)

SELECT NAME, DATETIME FROM ANIMAL_INS WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAl_OUTS ) ORDER BY DATETIME LIMIT 3

-- 오랜 기간 보호한 동물 문제(2)

SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_INS AS INS JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID ORDER BY INS.DATETIME - OUTS.DATETIME LIMIT 2

-- 없어진 기록 찾기

SELECT o.ANIMAL_ID, o.NAME FROM ANIMAL_INS as i RIGHT OUTER JOIN ANIMAL_OUTS as o ON i.ANIMAL_ID = o.ANIMAL_ID WHERE i.ANIMAL_ID IS NULL;